import React from "react";
import "./TermsAndConditions.css";
import Header from "../frontend/Header";
import TopBar from "../frontend/TopBar";
import Footer from "../frontend/Footer";


export default function TermsAndConditions() {
  return (
    <div className="terms-page">
        <TopBar />
                              <Header />
      <div className="terms-container">
        <h1 className="terms-title">Terms & Conditions</h1>
        <p className="terms-updated">Last updated: January 2026</p>

        <section>
          <p>
            This document (“Terms”) is an electronic record under the Information
            Technology Act, 2000 and rules made thereunder. This electronic
            record is generated by a computer system and does not require any
            physical or digital signatures.
          </p>

          <p>
            These Terms govern the access to and use of the website and mobile
            application <strong>www.bookmymedicare.com</strong>, operated by
            <strong> Axelia Solutions Private Limited</strong>.
          </p>
        </section>

        <section>
          <h2>1. General</h2>
          <p>
            BookMyMedicare is an e-commerce healthcare facilitation platform that
            connects customers with registered third-party healthcare service
            providers including laboratories, hospitals, diagnostic centers,
            homecare providers, and wellness services.
          </p>

          <p>
            By accessing or using the Website or Mobile Application, you agree
            to be bound by these Terms, the Privacy Policy, and all applicable
            laws in India.
          </p>
        </section>

        <section>
          <h2>2. Services</h2>
          <p>
            BookMyMedicare only acts as a facilitator. All healthcare services
            are provided directly by independent third-party service providers.
          </p>

          <p>
            The Company does not control, manage, or guarantee the quality,
            accuracy, or outcomes of services delivered by third parties.
          </p>
        </section>

        <section>
          <h2>3. Eligibility of Use</h2>
          <p>
            Use of the platform is available only to persons capable of entering
            into legally binding contracts under the Indian Contract Act, 1872.
          </p>

          <p>
            Minors may access services only through a legal guardian. The
            Company reserves the right to suspend or terminate access at its
            discretion.
          </p>
        </section>

        <section>
          <h2>4. Customer Account & Security</h2>
          <p>
            You are responsible for maintaining the confidentiality of your
            account credentials. All activities under your account are your
            responsibility.
          </p>

          <p>
            Any misuse, unauthorized access, or breach must be reported
            immediately to <strong>support@bookmymedicare.com</strong>.
          </p>
        </section>

        <section>
          <h2>5. Customer Obligations</h2>
          <ul>
            <li>Provide accurate and updated information</li>
            <li>Use the platform only for lawful purposes</li>
            <li>Not upload or transmit harmful, misleading, or illegal content</li>
            <li>Not attempt unauthorized access or data scraping</li>
          </ul>
        </section>

        <section>
          <h2>6. Intellectual Property Rights</h2>
          <p>
            All content, branding, trademarks, logos, and materials on the
            platform are owned by BookMyMedicare or its licensors and are
            protected under applicable intellectual property laws.
          </p>
        </section>

        <section>
          <h2>7. Membership</h2>
          <p>
            BookMyMedicare may offer subscription-based memberships. Memberships
            are non-transferable and non-refundable unless stated otherwise.
          </p>
        </section>

        <section>
          <h2>8. Advertisements</h2>
          <p>
            The platform may display advertisements from third-party partners.
            BookMyMedicare does not guarantee the accuracy of such advertisements.
          </p>
        </section>

        <section>
          <h2>9. Disclaimer of Warranties</h2>
          <p>
            The Website and services are provided on an “as is” and “as
            available” basis without warranties of any kind.
          </p>
        </section>

        <section>
          <h2>10. Limitation of Liability</h2>
          <p>
            BookMyMedicare shall not be liable for any indirect, incidental,
            consequential, or punitive damages arising from the use of the
            platform.
          </p>
        </section>

        <section>
          <h2>11. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless the Company from any claims,
            damages, or losses arising from your misuse of the platform or
            violation of these Terms.
          </p>
        </section>

        <section>
          <h2>12. Termination</h2>
          <p>
            The Company reserves the right to suspend or terminate your access
            at any time without notice for violations of these Terms.
          </p>
        </section>

        <section>
          <h2>13. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with
            the laws of India. Courts in Maharashtra shall have exclusive
            jurisdiction.
          </p>
        </section>
      </div>
      <Footer />
    </div>
  );
}
